# Generated by Django 2.0.1 on 2018-01-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfields',
            name='foreign_key',
        ),
        migrations.RemoveField(
            model_name='testfields',
            name='many_to_many_field',
        ),
    ]
