# Generated by Django 2.0.1 on 2018-01-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180127_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfields',
            name='file_path_field',
        ),
    ]
