# Generated by Django 2.0.1 on 2018-01-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_testfields_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfields',
            name='image_field',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
