# Generated by Django 2.0.1 on 2018-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20180127_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfields',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='testfields',
            name='image_field',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/uploads/%Y/%m/%d/'),
        ),
    ]
